version: "3"

services:
  php-professorarchibaald:
    build:
      context: .
      dockerfile: phpFpm/Dockerfile
    volumes:
      - ./phpFpm/php.ini:/usr/local/etc/php/php.ini
      - ${CODE_PATH_LOCAL}:${CODE_PATH_CONTAINER}
    container_name: php-professorarchibaald
    networks:
      - code-network
    environment:
      - NLS_LANG=RUSSIAN_RUSSIA.UTF8

  nginx-professorarchibaald:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - ${CODE_PATH_LOCAL}:${CODE_PATH_CONTAINER}
    ports:
      - ${NGINX_PORT}:80
    links:
      - php-professorarchibaald
    volumes:
      - ${CODE_PATH_LOCAL}:${CODE_PATH_CONTAINER}
    container_name: nginx-professorarchibaald
    networks:
      - code-network

networks:
  code-network:
    driver: bridge